# Puerto del servidor de la API
server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ong_mujeres_celebran_la_vida
spring.datasource.username=postgres
spring.datasource.password=Uruguay26..
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Encoding
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true